### ISSUE TITLE
Plugin shows up as having a "proprietary" license on Flathub page

### ISSUE THREAD

**Issue by MisterSheeple** [flathub/com.obsproject.Studio.Plugin.NDI#1]

**Comment by tytan652** [comment]
[License in Appstream file](https://github.com/flathub/com.obsproject.Studio.Plugin.NDI/blob/c5158e265ef5489b40442ecd00d0bc8e6e2f752e/com.obsproject.Studio.Plugin.NDI.metainfo.xml#L10)

|Element|License|
|------------|-----------|
|obs-ndi|GPL2-or-later|
|avahi (required by libndi)|LGPL-2.1-or-later|
|NDI headers in obs-ndi|MIT|
|libndi (from ndi-sdk)|[NDI License Agreement](https://downloads.ndi.tv/SDK/NDI_SDK/NDI%20License%20Agreement.pdf)(proprierary)|

PS: libndi is downloaded by the user while installing the plugin thanks to the `extra-data` feature, so we do not redistribute the library.
