### ISSUE TITLE
Aborted due to failure (Wrong size for extra data)

### ISSUE THREAD

**Issue by pollux56** [flathub/com.obsproject.Studio.Plugin.NDI#3]
trying to download the plugin through discover i get this error 

Aborted due to failure (Wrong size for extra data https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz)

same error when trying to install through terminal

error: Failed to install com.obsproject.Studio.Plugin.NDI: Wrong size for extra data https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz

opensuse tumbleweed
plasma 5.27.9

**Comment by tytan652** [comment]
This error will occur each time that the NDI SDK gets updated.
