### ISSUE TITLE
Problem with NDI runtime

### ISSUE THREAD

**Issue by socek** [flathub/com.obsproject.Studio.Plugin.NDI#6]
I've updated version for NDI (https://github.com/flathub/com.obsproject.Studio.Plugin.NDI/pull/5/commits/fc5c1e14367a34c0e95e9043fe8a5546af7bbb82) and tough it was running, but I made error in tests.
Now I see error:
![image](https://github.com/flathub/com.obsproject.Studio.Plugin.NDI/assets/317401/b3483887-a352-4e6a-bddc-168431b9f9f4)

I have no idea how to debug this.

**Comment by tytan652** [comment]
It works on my machine
```
info: [obs-ndi] load_ndilib: Trying '/app/plugins/NDI/extra/lib/libndi.so.5'
info: [obs-ndi] load_ndilib: Found NDI library at '/app/plugins/NDI/extra/lib/libndi.so.5'
info: [obs-ndi] load_ndilib: NDI runtime loaded successfully
info: [obs-ndi] load_ndilib: NDIlib_v5_load found
info: [obs-ndi] obs_module_load: NDI library initialized successfully ('NDI SDK LINUX 12:52:02 Feb 16 2024 5.6.1')
```

`NDI SDK LINUX 12:52:02 Feb 16 2024 5.6.1` is the part that proves that the update worked.

**Comment by tytan652** [comment]
At least provide a log from an OBS made with `flatpak run com.obsproject.Studio//stable --verbose`.
